import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UnifiedNavbar from "@/components/common/UnifiedNavbar";
import ErrorBoundary from "@/components/ErrorBoundary";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen`}
			>
				<ErrorBoundary>
					<UnifiedNavbar />
					<main className="min-h-screen">{children}</main>
				</ErrorBoundary>
			</body>
		</html>
	);
}
